In [3]:
import torch

In [5]:
#数学运算
a = torch.FloatTensor([2])
b= torch.FloatTensor([3])
a+b

tensor([5.])

In [7]:
am = torch.randn(3,3)
am

tensor([[-0.8621,  0.0076,  1.7272],
        [ 0.6023,  1.2379,  0.5435],
        [-0.4353, -0.7793,  1.0118]])

In [8]:
# 转置矩阵
am.t()

tensor([[-0.8621,  0.6023, -0.4353],
        [ 0.0076,  1.2379, -0.7793],
        [ 1.7272,  0.5435,  1.0118]])

In [4]:
from torch.autograd import Variable

train_x = torch.randn(10,5)
train_y = torch.randn(10,3)
x = Variable(train_x)
y = Variable(train_y, requires_grad=False)

In [11]:
# 神经网络模块
import torch

#define model
input_num_units = 64
hidden_num_units = 32
output_num_units = 10
model = torch.nn.Sequential(
    # 神经网络，即Dense
    torch.nn.Linear(input_num_units,hidden_num_units),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_num_units,output_num_units),
)
loss_fn = torch.nn.CrossEntropyLoss()

In [1]:
from __future__ import print_function

In [7]:
x = torch.empty(5,5)
x

tensor([[ 1.0048e-38,  1.4348e-19,  4.6246e+19,  8.3959e-33,  0.0000e+00],
        [ 0.0000e+00,  2.1019e-44,  0.0000e+00, -2.8127e+29,  4.6943e-43],
        [-5.5818e+30,  4.6943e-43, -5.5818e+30,  4.6943e-43, -5.5819e+30],
        [ 4.6943e-43, -2.8126e+29,  4.6943e-43,  1.9346e-19,  1.7750e+28],
        [ 6.8707e+19,  1.3563e-19,  1.3563e-19,  1.3563e-19,  1.3563e-19]])

In [8]:
x = torch.rand(5,5)
x

tensor([[0.1560, 0.0257, 0.5306, 0.1607, 0.1179],
        [0.0471, 0.7479, 0.8291, 0.5585, 0.6970],
        [0.0941, 0.6831, 0.1139, 0.5089, 0.1382],
        [0.2150, 0.8151, 0.6148, 0.3678, 0.0758],
        [0.3285, 0.4371, 0.5985, 0.4435, 0.0202]])

In [10]:
x = torch.zeros(5,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [11]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [14]:
x = x.new_ones(5, 3, dtype=torch.double)      
# new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    
# override dtype!
print(x)                                      
# result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4338, -0.6971,  0.4590],
        [ 0.4931,  0.9376, -1.0755],
        [ 0.8407, -0.1487, -0.2137],
        [ 0.0849,  0.5901, -0.6825],
        [ 1.7416, -1.1137,  0.2690]])


In [17]:
x.size()

torch.Size([5, 3])

In [18]:
y = torch.randn(5,3)

In [23]:
x+y == torch.add(x,y)

tensor([[-0.0305, -0.9060,  1.3084],
        [-0.7058,  1.1590, -3.2663],
        [ 0.0052, -1.0979, -0.6685],
        [-0.3480, -0.7873, -1.2687],
        [ 4.1115, -0.1884,  0.5863]])

In [25]:
# 在y上加x,这将改变y
y.add_(x)

tensor([[-0.0305, -0.9060,  1.3084],
        [-0.7058,  1.1590, -3.2663],
        [ 0.0052, -1.0979, -0.6685],
        [-0.3480, -0.7873, -1.2687],
        [ 4.1115, -0.1884,  0.5863]])

In [29]:
x[...,1]

tensor([-0.6971,  0.9376, -0.1487,  0.5901, -1.1137])

In [38]:
x = torch.rand(4,4)

# 转化成1维数据
x.view(16)

# 也可以使用-1进行自动匹配
x.view(-1,8)

torch.Size([2, 8])

In [43]:
x = torch.randn(1)
x.item()

-1.3435566425323486

In [44]:
x

tensor([-1.3436])

In [60]:
x = torch.ones(2, 2, requires_grad=True)
y = x +2

In [61]:
z = y * y * 3
out = z.mean()

out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [90]:
x = torch.ones(3,requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([1024., 1024., 1024.], grad_fn=<MulBackward0>)


In [91]:
v = torch.tensor([1,2,3],dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([1024., 2048., 3072.])


In [96]:
a = torch.rand(3,3)
a.size()[1:]

torch.Size([3])

In [97]:
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        # reshape成[batch,n]
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [98]:
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1's .weight

10
torch.Size([6, 1, 5, 5])


In [99]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0452,  0.1736,  0.1350,  0.0370,  0.0763, -0.0930, -0.0830, -0.0199,
          0.0330, -0.0945]], grad_fn=<AddmmBackward>)


In [100]:
net.zero_grad()
out.backward(torch.randn(1, 10))

In [101]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(0.4788, grad_fn=<MseLossBackward>)


In [102]:
# 清除原有梯度
net.zero_grad()

print(f'conv1.bias.grad before backward:{net.conv1.bias.grad}')
loss.backward()
print(f'conv1.bias.grad after backward:{net.conv1.bias.grad}')

conv1.bias.grad before backward:tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward:tensor([ 0.0039, -0.0035, -0.0028, -0.0059, -0.0020, -0.0033])


In [103]:
# 使用优化器方法
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()    # Does the update